---
apiVersion: v2
name: tssc-infrastructure
description: TSSC Infrastructure
type: application
version: "1.7.0"
annotations:
  tssc.redhat-appstudio.github.com/depends-on: tssc-openshift, tssc-subscriptions
