{{- $acs := .Values.acs -}}
---
apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  labels:
    app: acs
  name: {{
    required ".acs.name is required" $acs.name
  }} 
spec:
  monitoring:
    openshift:
      enabled: true
  central:
    db:
      isEnabled: Default
      persistence:
        persistentVolumeClaim:
          claimName: central-db
      resources: {{-
        required ".acs.central.db.resources is required"
          $acs.central.db.resources | toYaml | nindent 8
      }}
    exposure:
      loadBalancer:
        enabled: false
        port: 443
      nodePort:
        enabled: false
      route:
        enabled: true
    notifierSecretsEncryption:
      enabled: false
    persistence:
      persistentVolumeClaim:
        claimName: stackrox-db
    resources: {{-
      required ".acs.central.resources is required"
        $acs.central.resources | toYaml | nindent 6
    }}
    telemetry:
      enabled: true
  egress:
    connectivityPolicy: Online
  scannerV4:
    db:
      persistence:
        persistentVolumeClaim:
          claimName: scanner-v4-db
    indexer: {{-
      required ".acs.scanners.indexer is required"
        $acs.scanners.indexer | toYaml | nindent 6
    }}
    matcher: {{-
      required ".acs.scanners.matcher is required"
        $acs.scanners.matcher | toYaml | nindent 6
    }}
    scannerComponent: Enabled
  scanner:
    analyzer: {{-
      required ".acs.scanners.analyzer is required"
        $acs.scanners.analyzer | toYaml | nindent 6
    }}
