{{- $acs := .Values.acs -}}
{{- $name := printf "%s-post-deploy" $acs.name }}
#
# Generates a token for StackRox API.
#
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    {{- include "common.labels" . | nindent 4 }}
  name: {{ $name }}
spec:
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}
      restartPolicy: Never
      initContainers:
        #
        # Copying the scripts that will be used on the subsequent containers, the
        # scripts are shared via the "/scripts" volume.
        #
  {{- include "common.copyScripts" . | nindent 8 }}
      containers:
        #
        # Generates a token for StackRox API, using the ACS Central credentials.
        #
        - name: stackrox-api-generate-token
          image: quay.io/codeready-toolchain/oc-client-base:latest
          env:
            - name: ROX_ENDPOINT
              value: {{ include "acs.centralEndPoint" . }}
            - name: ROX_USERNAME
              value: admin
            - name: ROX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: central-htpasswd
                  key: password
            - name: SECRET_NAME
              value: {{ $acs.integrationSecret.name }}
            - name: NAMESPACE
              value: {{ $acs.integrationSecret.namespace }}
          command:
            - /scripts/stackrox-helper.sh
          volumeMounts:
            - name: scripts
              mountPath: /scripts
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: scripts
          emptyDir: {}
