{{- $integrations := (default dict .Values.integrations) -}}
{{- $data := (default dict $integrations.github) -}}
{{- if $data }}
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: rhtap-github-integration
stringData:
  id: {{ $data.id | quote }}
  clientID: {{ $data.clientId }}
  clientSecret: {{ $data.clientSecret }}
  host: {{ $data.host }}
  pem: |
{{ $data.publicKey | indent 4 }}
  token: {{ $data.token }}
  webhookSecret: {{ $data.webhookSecret }}
{{- end }}