---
rhtapInstallerCLI:
  namespace: &installerNamespace rhtap
  features:
    crc:
      enabled: true
    trustedProfileAnalyzer:
      enabled: &tpaEnabled true
      namespace: &trustedProfileAnalyzerNamespace rhtap-tpa
    keycloak:
      enabled: *tpaEnabled
      namespace: rhtap-keycloak
    trustedArtifactSigner:
      enabled: false
      namespace: &trustedArtifactSignerNamespace rhtap-tas
    redHatDeveloperHub:
      enabled: &rhdhEnabled true
      namespace: rhdh-operator
    redHatQuay:
      enabled: true
      namespace: rhtap-quay
    openShiftPipelines:
      enabled: *rhdhEnabled
      namespace: openshift-pipelines
  dependencies:
    - chart: charts/rhtap-openshift
      namespace: *installerNamespace
    - chart: charts/rhtap-subscriptions
      namespace: *installerNamespace
    - chart: charts/rhtap-infrastructure
      namespace: *installerNamespace
    - chart: charts/rhtap-backing-services
      namespace: *installerNamespace
    - chart: charts/rhtap-integrations
      namespace: *installerNamespace
    - chart: charts/rhtap-tas
      namespace: *trustedArtifactSignerNamespace
    - chart: charts/rhtap-tpa
      namespace: *trustedProfileAnalyzerNamespace
    - chart: charts/rhtap-dh
      namespace: *installerNamespace
