{{- if .Values.minIOOperator.enabled }}
  {{- $sa := include "rhtapMinioOperator.serviceAccountName" . -}}
  {{- $namespace := .Release.Namespace -}}
  {{- $saAdmin := printf "%s-admin" $sa -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: minio-operator
    {{- include "rhtap-minio-operator.labels" . | nindent 4 }}
  name: {{ $saAdmin }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ $sa }}
    namespace: {{ $namespace }}
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  labels:
    app: minio-operator
    {{- include "rhtap-minio-operator.labels" . | nindent 4 }}
  name: {{ $sa }}
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAs
  uid: 1000
fsGroup:
  type: MustRunAs
  ranges:
    - min: 1000
      max: 1000
seLinuxContext:
  type: MustRunAs
users:
  - {{ printf "system:serviceaccount:%s:%s" $namespace $sa }}
{{- end }}
