{{ $namespace := .Release.Namespace }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "rhtap-artifactory-integration") | default dict -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
{{- if $secretData }}
  {{- range tuple "development" "prod" "stage" }}
---
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: artifactory-auth
  namespace: {{ $namespace }}-app-{{ . }}
data:
  .dockerconfigjson: {{ get $secretData ".dockerconfigjson" }}
  {{- end }}
{{- end }}
