---
apiVersion: v2
name: tssc-iam
description: TSSC IAM
type: application
version: "1.7.0"
annotations:
  tssc.redhat-appstudio.github.com/depends-on: tssc-openshift, tssc-subscriptions, tssc-infrastructure
