---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        rhdh.redhat.com/backstage-name: {{ .Values.developerHub.instanceName | quote }}
    labels:
        rhdh.redhat.com/ext-config-sync: "true"
    name: developer-hub-rhtap-env
    namespace: {{ .Release.Namespace }}
type: Opaque
data:
    BACKEND_SECRET: {{ randAlphaNum 16 | b64enc }}
    BACKEND_URL: {{ printf "https://backstage-developer-hub-%s.%s" .Release.Namespace .Values.developerHub.ingressDomain | b64enc }}
    NODE_TLS_REJECT_UNAUTHORIZED:  {{ "0" | b64enc }}
{{- $argocdSecretObj := (lookup "v1" "Secret" .Release.Namespace "rhtap-argocd-integration") }}
{{- $argocdSecretData := ($argocdSecretObj.data | default dict) }}
{{- if $argocdSecretData }}
    ARGOCD__API_TOKEN: {{ $argocdSecretData.ARGOCD_API_TOKEN }}
    ARGOCD__PASSWORD: {{ $argocdSecretData.ARGOCD_PASSWORD }}
    ARGOCD__URL: {{ print "https://" ($argocdSecretData.ARGOCD_HOSTNAME | b64dec) | b64enc }}
    ARGOCD__USER: {{ $argocdSecretData.ARGOCD_USER }}
{{- end }}
    DEVELOPER_HUB__CATALOG__URL: {{
        required ".developerHub.catalogURL is required" .Values.developerHub.catalogURL | b64enc
    }}
{{- $bbSecretObj := (lookup "v1" "Secret" .Release.Namespace "rhtap-bitbucket-integration") }}
{{- $bbSecretData := ($bbSecretObj.data | default dict) }}
    BITBUCKET_WORKSPACE: {{ get $bbSecretData "workspace" | default ("#unset" | b64enc) }}
{{- $ghSecretObj := (lookup "v1" "Secret" .Release.Namespace "rhtap-github-integration") }}
{{- $ghSecretData := ($ghSecretObj.data | default dict) }}
{{- if $ghSecretData }}
    GITHUB__APP__ID: {{ $ghSecretData.id }}
    GITHUB__APP__CLIENT__ID: {{ $ghSecretData.clientID }}
    GITHUB__APP__CLIENT__SECRET: {{ $ghSecretData.clientSecret }}
    GITHUB__APP__PRIVATE_KEY: {{ $ghSecretData.pem }}
    GITHUB__APP__WEBHOOK__SECRET: {{ $ghSecretData.webhookSecret }}
    {{- $pacRoute := (lookup "route.openshift.io/v1" "Route" "openshift-pipelines" "pipelines-as-code-controller") }}
    {{- if $pacRoute }}
    GITHUB__APP__WEBHOOK__URL: {{ print "https://" $pacRoute.spec.host | b64enc }}
    GITHUB__HOST: {{ $ghSecretData.host }}
    GITHUB__URL: {{ print "https://" ($ghSecretData.host | b64dec) | b64enc }}
    {{- end }}
{{- end }}
{{- $glSecretObj := (lookup "v1" "Secret" .Release.Namespace "rhtap-gitlab-integration") -}}
{{- $glSecretData := ($glSecretObj.data | default dict) -}}
{{- if $glSecretData }}
    GITLAB__HOST: {{ $glSecretData.host }}
    GITLAB__TOKEN: "{{ $glSecretData.token }}"
{{- end }}
{{- $jenkinsSecretObj := (lookup "v1" "Secret" .Release.Namespace "rhtap-jenkins-integration") }}
{{- $jenkinsSecretData := ($jenkinsSecretObj.data | default dict) }}
{{- if $jenkinsSecretData }}
    JENKINS__BASEURL: {{ $jenkinsSecretData.baseUrl }}
    JENKINS__USERNAME: {{ $jenkinsSecretData.username }}
    JENKINS__TOKEN: {{ $jenkinsSecretData.token }}
{{- end }}
{{- $k8sSecretObj := (lookup "v1" "Secret" .Release.Namespace "rhtap-k8s-integration") }}
{{- $k8sSecretData := ($k8sSecretObj.data | default dict) }}
{{- if $k8sSecretData }}
    K8S_SERVICEACCOUNT_TOKEN: {{ $k8sSecretData.token }}
{{- end }}
{{- $artifactorySecretObj := (lookup "v1" "Secret" .Release.Namespace "rhtap-artifactory-integration") }}
{{- $artifactorySecretData := ($artifactorySecretObj.data | default dict) }}
{{- if $artifactorySecretData }}
    ARTIFACTORY__API_TOKEN: {{ $artifactorySecretData.token }}
    ARTIFACTORY__URL: {{ $artifactorySecretData.url }}
{{- end }}
{{- $nexusSecretObj := (lookup "v1" "Secret" .Release.Namespace "rhtap-nexus-integration") }}
{{- $nexusSecretData := ($nexusSecretObj.data | default dict) }}
{{- if $nexusSecretData }}
    NEXUS__URL: {{ $nexusSecretData.url }}
{{- end }}
{{- $quaySecretObj := (lookup "v1" "Secret" .Release.Namespace "rhtap-quay-integration") }}
{{- $quaySecretData := ($quaySecretObj.data | default dict) }}
{{- if $quaySecretData }}
    {{- if $quaySecretData.token }}
    QUAY__API_TOKEN: {{ $quaySecretData.token }}
    {{- end }}
    QUAY__URL: {{ $quaySecretData.url }}
{{- end }}
