{{- define "rhtap-dh.plugins-conf" }}
{{- $integrationNamespace := .Values.developerHub.integrationSecrets.namespace }}
includes:
  - dynamic-plugins.default.yaml
plugins:
  # Installed plugins can be listed at:
  # https://DH_HOSTNAME/api/dynamic-plugins-info/loaded-plugins
{{- if (lookup "v1" "Secret" $integrationNamespace "rhtap-argocd-integration") }}
  #
  # ArgoCD
  #
  - disabled: false
    package: ./dynamic-plugins/dist/backstage-community-plugin-redhat-argocd
  - disabled: false
    package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd-backend-dynamic
    pluginConfig:
      argocd:
        appLocatorMethods:
          - type: 'config'
            instances: []
  - disabled: false
    package: ./dynamic-plugins/dist/roadiehq-scaffolder-backend-argocd-dynamic
    pluginConfig:
      argocd:
        appLocatorMethods:
          - type: 'config'
            instances: []
{{- end }}
  #
  # CI
  #
  - disabled: false
    package: ./dynamic-plugins/dist/backstage-community-plugin-tekton
    pluginConfig:
      dynamicPlugins:
        frontend:
          backstage-community.plugin-tekton:
            mountPoints:
              - config:
                  if:
                    allOf:
                      - isTektonCIAvailable
                  layout:
                    gridColumn: 1 / -1
                    gridRowStart: 1
                importName: TektonCI
                mountPoint: entity.page.ci/cards
{{- if (lookup "v1" "Secret" $integrationNamespace "rhtap-azure-integration") }}
  - disabled: false
    package: ./dynamic-plugins/dist/backstage-community-plugin-azure-devops-backend-dynamic
  - disabled: false
    package: ./dynamic-plugins/dist/backstage-community-plugin-azure-devops
    # The default pluginConfig also includes EntityAzurePullRequestsContent which is not supported
    # in RHTAP and causes 500 errors when loading the PR/MR tab:
    # https://issues.redhat.com/browse/RHTAP-4837
    pluginConfig:
      dynamicPlugins:
        frontend:
          backstage-community.plugin-azure-devops:
            mountPoints:
              - mountPoint: entity.page.ci/cards
                importName: EntityAzurePipelinesContent
                config:
                  layout:
                    gridColumn: "1 / -1"
                  if:
                    allOf:
                      - isAzureDevOpsAvailable
{{- end }}
{{- if (lookup "v1" "Secret" $integrationNamespace "rhtap-github-integration") }}
  - disabled: false
    package: ./dynamic-plugins/dist/backstage-community-plugin-github-actions
{{- end }}
{{- if (lookup "v1" "Secret" $integrationNamespace "rhtap-gitlab-integration") }}
  - disabled: false
    package: ./dynamic-plugins/dist/immobiliarelabs-backstage-plugin-gitlab
  - disabled: false
    package: ./dynamic-plugins/dist/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic
{{- end }}
{{- if (lookup "v1" "Secret" $integrationNamespace "rhtap-jenkins-integration") }}
  - disabled: false
    package: ./dynamic-plugins/dist/backstage-community-plugin-jenkins
    pluginConfig:
      dynamicPlugins:
        frontend:
          backstage-community.plugin-jenkins:
            mountPoints:
              - mountPoint: entity.page.ci/cards
                importName: EntityJenkinsContent
                config:
                  layout:
                    gridColumn: "1 / -1"
                  if:
                    allOf:
                      - isJenkinsAvailable
  - disabled: false
    package: ./dynamic-plugins/dist/backstage-community-plugin-jenkins-backend-dynamic
{{- end }}
  - disabled: false
    package: oci://registry.redhat.io/rhtap-backstage-plugins/rhtap-backstage-plugins-artifacts:1.5.0!rhtap-plugins-backstage-community-plugin-multi-source-security-viewer-dynamic
    pluginConfig:
      dynamicPlugins:
        frontend:
          rhtap-plugins.backstage-community-plugin-multi-source-security-viewer:
            mountPoints:
              - config:
                  layout:
                    gridColumn: 1 / -1
                    gridRowStart: 2
                  if:
                    allOf:
                      - isMultiCIAvailable
                importName: EntityMultiCIPipelinesContent
                mountPoint: entity.page.ci/cards
            entityTabs:
              - path: /ci
                title: CI
                mountPoint: entity.page.ci
  #
  # Git
  #
  # The all the git plugins are always enabled as they are referenced by the default templates
  - disabled: false
    package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-bitbucket-cloud-dynamic
  - disabled: false
    package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-github-dynamic
  - disabled: false
    package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-gitlab-dynamic
  #
  # Image Registry
  #
{{- if (lookup "v1" "Secret" $integrationNamespace "rhtap-artifactory-integration") }}
  - disabled: false
    package: ./dynamic-plugins/dist/backstage-community-plugin-jfrog-artifactory
{{- end }}
{{- if (lookup "v1" "Secret" $integrationNamespace "rhtap-nexus-integration") }}
  - disabled: false
    package: ./dynamic-plugins/dist/backstage-community-plugin-nexus-repository-manager
{{- end }}
{{- if (lookup "v1" "Secret" $integrationNamespace "rhtap-quay-integration") }}
  - disabled: false
    package: ./dynamic-plugins/dist/backstage-community-plugin-quay
{{- end }}
  #
  # Kubernetes
  #
  - disabled: false
    package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
  - disabled: false
    package: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
    pluginConfig:
      kubernetes:
        clusterLocatorMethods:
          - clusters:
              - authProvider: serviceAccount
                customResources:
                  - group: argoproj.io
                    apiVersion: v1alpha1
                    plural: rollouts
                  - apiVersion: v1
                    group: route.openshift.io
                    plural: routes
                  - apiVersion: v1
                    group: tekton.dev
                    plural: pipelineruns
                  - apiVersion: v1
                    group: tekton.dev
                    plural: taskruns
                name: rhdh-cluster
                serviceAccountToken: ${K8S_SERVICEACCOUNT_TOKEN}
                skipTLSVerify: true
                url: https://kubernetes.default.svc
            type: config
        serviceLocatorMethod:
          type: multiTenant
  - disabled: false
    package: ./dynamic-plugins/dist/backstage-community-plugin-topology
  #
  # RBAC
  #
  {{- $githubSecretObj := (lookup "v1" "Secret" $integrationNamespace "rhtap-github-integration") }}
  {{- if and .Values.developerHub.RBAC.enabled $githubSecretObj }}
  - package: ./dynamic-plugins/dist/backstage-community-plugin-rbac
    disabled: false
  - package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-org-dynamic
    disabled: false
    pluginConfig:
      catalog:
        githubOrg:
          githubUrl: ${GITHUB__URL}
  {{- end}}
  #
  # Tech Docs
  #
  - disabled: false
    package: ./dynamic-plugins/dist/backstage-plugin-techdocs
  - disabled: false
    package: ./dynamic-plugins/dist/backstage-plugin-techdocs-backend-dynamic
{{- end }}
