{{- $secretObj := (lookup "v1" "Secret" "openshift-pipelines" "signing-secrets") -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
{{- if $secretData -}}
  {{- range .Values.appNamespaces.namespace_prefixes }}
    {{- $namespace := . }}
---
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: cosign-pub
  namespace: {{ $namespace }}-ci
data:
  cosign.pub: {{ index $secretData "x509-pub.pem" }}
  {{- end }}
{{- end }}