{{ $namespace := .Release.Namespace }}
{{- $secretObj := (lookup "v1" "Secret" "openshift-pipelines" "signing-secrets") -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
{{- if $secretData -}}
---
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: cosign-pub
  namespace: {{ $namespace }}-app-development
data:
  cosign.pub: {{ index $secretData "cosign.pub" }}
{{- end }}