---
apiVersion: v2
name: tssc-tpa-realm
description: TSSC Trusted Profile Analyzer Keycloak Chicken realm import
type: application
version: "1.7.0"
annotations:
  tssc.redhat-appstudio.github.com/use-product-namespace: Trusted Profile Analyzer
