{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "rhtap-github-integration") -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
{{- if $secretData -}}
{{- range tuple "development" "prod" "stage" }}
---
kind: Secret
type: kubernetes.io/basic-auth
apiVersion: v1
metadata:
  name: gitops-auth-token
  namespace: rhtap-app-{{ . }}
data:
  password: {{ $secretData.Token }}
{{- end }}
{{- end }}