apiVersion: v2
name: tssc-dh
description: Red Hat Developer Hub
type: application
version: "1.6.0"
appVersion: "1.6"
annotations:
  tssc.redhat-appstudio.github.com/product-name: Developer Hub
  tssc.redhat-appstudio.github.com/depends-on: tssc-openshift, tssc-subscriptions, tssc-infrastructure, tssc-gitops, tssc-tas, tssc-pipelines, tssc-tpa, tssc-app-namespaces
