---
apiVersion: v2
name: tssc-gitops
description: TSSC OpenShift GitOps
type: application
version: "1.6.0"
appVersion: "1.17"
annotations:
  tssc.redhat-appstudio.github.com/product-name: OpenShift GitOps
  tssc.redhat-appstudio.github.com/depends-on: tssc-openshift, tssc-subscriptions
