---
subscriptions:
  amqStreams:
    enabled: false
    description: Red Hat AMQ Streams
    apiResource: kafkas.kafka.strimzi.io 
    namespace: openshift-operators
    name: amq-streams
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  crunchyData:
    enabled: false
    description: Crunchy-Data PostgreSQL Operator
    apiResource: postgresclusters.postgres-operator.crunchydata.com
    namespace: openshift-operators
    name: crunchy-postgres-operator-rhmp
    channel: v5
    source: redhat-marketplace
    sourceNamespace: openshift-marketplace            
  minIO:
    enabled: false
    description: MinIO Operator
    apiResource: tenants.minio.min.io
    namespace: minio-operator
    name: minio-operator
    channel: stable
    source: certified-operators
    sourceNamespace: openshift-marketplace
    operatorGroup:
      upgradeStrategy: Default
  openshiftGitOps:
    enabled: false
    description: OpenShift GitOps Operator
    apiResource: gitopsservices.pipelines.openshift.io
    namespace: openshift-operators
    name: openshift-gitops-operator
    channel: gitops-1.12
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    config:
      argoCDClusterNamespace: __OVERWRITE_ME__
  openshiftKeycloak:
    enabled: false
    description: Red Hat Keycloak Operator
    apiResource: keycloaks.k8s.keycloak.org
    namespace: rhbk-operator
    name: rhbk-operator
    channel: stable-v22
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    operatorGroup:
      upgradeStrategy: Default
      targetNamespaces: []
  openshiftPipelines:
    enabled: false
    description: OpenShift Pipelines Operator
    apiResource: pipelines.tekton.dev
    namespace: openshift-operators
    name: openshift-pipelines-operator-rh
    channel: pipelines-1.14
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  openshiftTrustedArtifactSigner:
    enabled: false
    description: Red Hat Trusted Artifact Signer Operator
    apiResource: securesigns.rhtas.redhat.com
    namespace: openshift-operators
    name: rhtas-operator
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace
