#
# Workaround
# Applies the TektonConfig via a kubectl instead of letting Helm
# manage the resource.
# This should be reverted once the issue has been fixed in
# Openshift Pipelines (1.16).
#
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
  labels:
    {{- include "rhtap-pipelines.labels" . | nindent 4 }}
  name: tekton-post-deploy
spec:
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}
      restartPolicy: Never
      containers:
        - name: update-tektonconfig
          image: quay.io/codeready-toolchain/oc-client-base:latest
          resources:
            limits:
              cpu: 125m
              memory: 256Mi
              ephemeral-storage: 100Mi
          command:
            - /bin/bash
            - -c
            - |
              set -o errexit
              set -o nounset
              set -o pipefail

              cat <<EOF | kubectl apply -f -
{{ include "pipelines.tektonconfig" . | indent 14 }}
              EOF

              echo "Success"
          workingDir: /tmp
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
            requests:
              cpu: 100m
              ephemeral-storage: 256Mi
              memory: 256Mi
          securityContext:
            runAsNonRoot: false
            allowPrivilegeEscalation: false
      automountServiceAccountToken: true
