---
apiVersion: v2
name: tssc-tpa
description: RHTAP Trusted Profile Analyzer
type: application
version: 1.5.0
appVersion: "2.0.0"
dependencies:
  - name: redhat-trusted-profile-analyzer
    version: 1.0.0
    condition: trustedProfileAnalyzer.enabled
