---
rhtapCLI:
  namespace: &installerNamespace rhtap
  features:
    crc:
      enabled: false
    trustedProfileAnalyzer:
      enabled: &tpaEnabled true
      namespace: &trustedProfileAnalyzerNamespace rhtap-tpa
    keycloak:
      enabled: *tpaEnabled
      namespace: rhtap-keycloak
    trustedArtifactSigner:
      enabled: &tasEnabled true
      namespace: &trustedArtifactSignerNamespace rhtap-tas
    redHatDeveloperHub:
      enabled: &rhdhEnabled true
      namespace: *installerNamespace
      properties:
        catalogURL: https://github.com/redhat-appstudio/tssc-sample-templates/blob/v1.3.0/all.yaml
    redHatAdvancedClusterSecurity:
      enabled: &rhacsEnabled true
      namespace: &rhacsNamespace rhtap-acs
    redHatQuay:
      enabled: &quayEnabled true
      namespace: &quayNamespace rhtap-quay
    openShiftGitOps:
      enabled: &gitopsEnabled true
      namespace: *installerNamespace
    openShiftPipelines:
      enabled: &pipelinesEnabled true
      # No new resources will be created in the namespace
      namespace: openshift-pipelines
  dependencies:
    - chart: charts/rhtap-openshift
      namespace: *installerNamespace
      enabled: true
    - chart: charts/rhtap-subscriptions
      namespace: *installerNamespace
      enabled: true
    - chart: charts/rhtap-minio-operator
      namespace: minio-operator
      enabled: true
    - chart: charts/rhtap-infrastructure
      namespace: *installerNamespace
      enabled: true
    - chart: charts/rhtap-integrations
      namespace: *installerNamespace
      enabled: true
    - chart: charts/rhtap-backing-services
      namespace: *installerNamespace
      enabled: *tpaEnabled
    - chart: charts/rhtap-acs
      namespace: *rhacsNamespace
      enabled: *rhacsEnabled
    - chart: charts/rhtap-gitops
      namespace: *installerNamespace
      enabled: *gitopsEnabled
    - chart: charts/rhtap-pipelines
      namespace: *installerNamespace
      enabled: *pipelinesEnabled
    - chart: charts/rhtap-quay
      namespace: *quayNamespace
      enabled: *quayEnabled
    - chart: charts/rhtap-tas
      namespace: *trustedArtifactSignerNamespace
      enabled: *tasEnabled
    - chart: charts/rhtap-tpa
      namespace: *trustedProfileAnalyzerNamespace
      enabled: *tpaEnabled
    - chart: charts/rhtap-app-namespaces
      namespace: *installerNamespace
      enabled: *pipelinesEnabled
    - chart: charts/rhtap-dh
      namespace: *installerNamespace
      enabled: *rhdhEnabled
    - chart: charts/rhtap-acs-scanner
      namespace: *installerNamespace
      enabled: *rhacsEnabled
