---
rhtapCLI:
  namespace: &installerNamespace rhtap
  features:
    crc:
      enabled: false
    trustedProfileAnalyzer:
      enabled: &tpaEnabled true
      namespace: &trustedProfileAnalyzerNamespace rhtap-tpa
    keycloak:
      enabled: *tpaEnabled
      namespace: rhtap-keycloak
    trustedArtifactSigner:
      enabled: &tasEnabled true
      namespace: &trustedArtifactSignerNamespace rhtap-tas
    redHatDeveloperHub:
      enabled: &rhdhEnabled true
      namespace: *installerNamespace
      properties:
        catalogURL: https://github.com/redhat-appstudio/tssc-sample-templates/blob/release/all.yaml
    redHatAdvancedClusterSecurity:
      enabled: *rhdhEnabled
      namespace: rhtap-acs
    redHatQuay:
      enabled: true
      namespace: rhtap-quay
    openShiftGitOps:
      enabled: *rhdhEnabled
      namespace: *installerNamespace
    openShiftPipelines:
      enabled: *rhdhEnabled
      # No new resources will be created in the namespace
      namespace: openshift-pipelines
  dependencies:
    - chart: charts/rhtap-openshift
      namespace: *installerNamespace
      enabled: true
    - chart: charts/rhtap-subscriptions
      namespace: *installerNamespace
      enabled: true
    - chart: charts/rhtap-minio-operator
      namespace: minio-operator
      enabled: true
    - chart: charts/rhtap-infrastructure
      namespace: *installerNamespace
      enabled: true
    - chart: charts/rhtap-integrations
      namespace: *installerNamespace
      enabled: true
    - chart: charts/rhtap-backing-services
      namespace: *installerNamespace
      enabled: true
    - chart: charts/rhtap-gitops
      namespace: *installerNamespace
      enabled: true
    - chart: charts/rhtap-pipelines
      namespace: *installerNamespace
      enabled: true
    - chart: charts/rhtap-tas
      namespace: *trustedArtifactSignerNamespace
      enabled: *tasEnabled
    - chart: charts/rhtap-tpa
      namespace: *trustedProfileAnalyzerNamespace
      enabled: *tpaEnabled
    - chart: charts/rhtap-dh
      namespace: *installerNamespace
      enabled: *rhdhEnabled
